apiVersion: apps/v1
kind: Deployment
metadata:
  name: addon-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: search-engine-alpha
  template:
    metadata:
      labels:
        app: search-engine-alpha
    spec:
      containers:
      - name: my-app
        image: httpd:latest
        ports:
        - containerPort: 5009
---
 apiVersion: v1
 kind: Service
 metadata:
   name: my-service
 spec:
   selector:
     app: search-engine-alpha
   ports:
       - name: http
         protocol: TCP
         port: 80
         targetPort: 80
